//---------- Built-In Events -------------------------------------------------//

//---------- Events ----------------------------------------------------------//
export const EVENT_RUN                    = 'run'
export const EVENT_STOP                   = 'stop'
export const EVENT_LOAD                   = 'load'
export const EVENT_CHANGES_COUNT          = 'change:changesCount'
export const EVENT_COMPONENT_SELECTED     = 'component:selected'
export const EVENT_ASSET_UPLOAD_START     = 'asset:upload:start'
export const EVENT_ASSET_UPLOAD_RESPONSE  = 'asset:upload:response'
export const EVENT_ASSET_UPLOAD_END       = 'asset:upload:end'
export const EVENT_ASSET_UPLOAD_ERROR     = 'asset:upload:error'
export const EVENT_STORAGE                = 'storage'
export const EVENT_STORAGE_START          = 'storage:start'
export const EVENT_STORAGE_END            = 'storage:end'
export const EVENT_STORAGE_ERROR          = 'storage:error'
export const EVENT_STORAGE_START_LOAD     = 'storage:start:load'
export const EVENT_STORAGE_END_LOAD       = 'storage:end:load'
export const EVENT_STORAGE_START_STORE    = 'storage:start:store'
export const EVENT_STORAGE_END_STORE      = 'storage:start:store'
